apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: hm-brille-api
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teamdigihot
  secretName: hm-brille-api-unleash-api-token
  environment: development
