apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hm-brille-api-alert
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  groups:
    - name: hm-brille-api-alerts
      rules:
        - alert: hm-brille-api - Applikasjonen er nede
          expr: kube_deployment_status_replicas_available{deployment="hm-brille-api"} == 0
          for: 2m
          annotations:
            consequence: "hm-brille-api er utilgjengelig"
            action: "`kubectl describe pod -l app=hm-brille-api -n teamdigihot` for events, og `kubectl logs -l app=hm-brille-api -n teamdigihot` for logger"
          labels:
            namespace: teamdigihot
            severity: critical
            special_type_to_use_in_alertmanager_config: hm-brille-api-alert-manager
            alert_type: custom

        - alert: test alert will always trigger
          expr: container_memory_working_set_bytes{namespace="teamdigihot", container="hm-brille-api"} > 99
          for: 1m
          annotations:
            consequence: "_*{{ $labels.container }}*_ has a working set of {{ $value }} bytes, there is no consequence"
            action: "no need to do _anything_"
            documentation: "https://prometheus.io/docs/prometheus/latest/querying/basics/"
            summary: "Container _*{{ $labels.container }}*_ has a working set of {{ $value }} bytes."
            sla: "no need to respond"
            special_type_to_use_in_alertmanager_config: hm-brille-api-alert-manager
            alert_type: custom

        - alert: hm-brille-api - Høy feilrate i logger
          expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="hm-brille-api",log_level=~"Warning|Error"}[3m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="hm-brille-api"}[3m]))) > 10
          for: 3m
          annotations:
            consequence: "høy feilrate i loggene for hm-brille-api"
            action: "Sjekk loggene til app hm-brille-api i namespace teamdigihot, for å se hvorfor det er så mye feil"
          labels:
            namespace: teamdigihot
            severity: warning
            special_type_to_use_in_alertmanager_config: hm-brille-api-alert-manager
            alert_type: custom