apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: hm-brille-api-job-sync-tss
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  restartPolicy: Never
  image: {{ image }}
  port: {{ port }}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
    - name: GIT_COMMIT
      value: {{commit}}
    - name: CRONJOB_TYPE
      value: SYNC_TSS
  envFrom:
    - secret: redis-password
    - secret: hm-soknad-api-secret
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
      {{#each inbound-applications}}
        - application: {{ this }}
      {{/each}}
    outbound:
      rules:
      {{#each outbound-applications}}
        - application: {{ this }}
      {{/each}}
        - application: syfohelsenettproxy
          namespace: teamsykmelding
          cluster: {{ syfohelsenettproxy_cluster }}
        - application: medlemskap-oppslag
          namespace: medlemskap
          cluster: {{ medlemskap_cluster }}
        - application: brille-redis
      external:
      {{#each external-hosts}}
        - host: {{ this }}
      {{/each}}
  kafka:
    pool: {{ kafka-cluster }}
  gcp:
    sqlInstances:
      - name: {{ db_instance_name }}
        type: POSTGRES_13
        tier: {{ db_tier }}
        diskType: SSD
        highAvailability: {{ db_high_availability }}
        diskSize: {{ db_size }}
        diskAutoresize: true
        autoBackupTime: "03:00"
        retainedBackups: {{ db_retained_backups }}
        databases:
          - name: {{ db_name }}
            envVarPrefix: DB
        cascadingDelete: false
  secureLogs:
    enabled: true