---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{ appnavn }}
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  team: teamdigihot
  port: {{ port }}
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  liveness:
    path: /internal/is-alive
    initialDelay: 50
    timeout: 1
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /internal/is-ready
    initialDelay: 50
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 3000Mi
    requests:
      cpu: 40m
      memory: 1256Mi
  env:
  {{#each env}}
     - name: {{@key }}
       value: "{{this}}"
  {{/each}}
     - name: GIT_COMMIT
       value: {{commit}}
  envFrom:
    - secret: redis-password
    - secret: hm-soknad-api-secret
    - secret: hm-slack-hook
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: false
      claims:
        extra:
          - "NAVident"
        groups:
        {{#each azure-group-ids}}
          - id: {{ this }}
        {{/each}}
  accessPolicy:
    inbound:
      rules:
      {{#each inbound-applications}}
        - application: {{ this }}
      {{/each}}
        - application: azure-token-generator
          namespace: aura
        - application: syfohelsenettproxy
          namespace: teamsykmelding
    outbound:
      rules:
      {{#each outbound-applications}}
         - application: {{ this }}
      {{/each}}
         - application: syfohelsenettproxy
           namespace: teamsykmelding
           cluster: {{ syfohelsenettproxy_cluster }}
         - application: medlemskap-oppslag
           namespace: medlemskap
           cluster: {{ medlemskap_cluster }}
         - application: medlemskap-barn
           namespace: medlemskap
           cluster: {{ medlemskap_cluster }}
         - application: brille-redis
      external:
      {{#each external-hosts}}
        - host: {{ this }}
      {{/each}}
  prometheus:
    enabled: true
    path: /internal/metrics
  kafka:
    pool: {{ kafka-cluster }}
  leaderElection: true
  gcp:
    sqlInstances:
      - name: {{ db_instance_name }}
        type: POSTGRES_13
        tier: {{ db_tier }}
        diskType: SSD
        highAvailability: {{ db_high_availability }}
        diskSize: {{ db_size }}
        diskAutoresize: true
        autoBackupTime: "03:00"
        retainedBackups: {{ db_retained_backups }}
        databases:
          - name: {{ db_name }}
            envVarPrefix: DB
            users:
              - name: naisjob
        cascadingDelete: false
  secureLogs:
    enabled: true
